image:
- Visual Studio 2019

environment:
  PY_DIR: C:/Python38-x64

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
  - cmd: echo "Downloading conan..."
  - cmd: echo %PATH%
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install conan
  - cmd: conan user
  - cmd: conan --version

build_script: 
  - cmd: conan remote add magic_get https://api.bintray.com/conan/yehorka9991/magic_get
  - cmd: conan install .
  - cmd: conan create . yehorka/stable